name: bid_express
description: BidExpress app

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  another_flushbar:
  animate_do:
  auto_size_text:
  bloc:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_screenutil:
  flutter_svg:
  http:
  image_picker:
  shared_preferences:
  page_transition:
  intl:
  google_maps_flutter:
  geolocator:
  permission_handler:
  connectivity_plus:
  lottie:
  pin_code_fields:
  timer_count_down:
  logger:
  country_code_picker:
  device_preview:
  json_reflectable: ^1.0.1
  json_annotation: ^4.8.1
  cached_network_image:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  json_serializable:





flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
