name: bid_express
description: BidExpress app

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  another_flushbar:
  animate_do:
  auto_size_text:
  bloc:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_screenutil:
  flutter_svg:
  http:
  image_picker:
  shared_preferences:
  page_transition:
  intl:
  google_maps_flutter:
  geolocator:
  permission_handler:
  connectivity_plus:
  lottie:
  pin_code_fields:
  timer_count_down:
  logger:
  country_code_picker:
  device_preview:
  json_reflectable: ^1.0.1
  json_annotation: ^4.8.1
  cached_network_image:
  location:
  easy_localization:
  isar:
  isar_flutter_libs:
  shimmer:
  dotted_border:
  flutter_animated_dialog:
  url_launcher:
  timeago: ^3.6.1
  flutter_onboarding_slider: ^1.0.11
  overlay_tooltip: ^0.2.3


dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable:
  isar_generator:





flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/
    - assets/lotties/
    - assets/translations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: SofiaProSoft
      fonts:
        - asset: assets/fonts/Sofia-Pro-Soft-Bold.ttf
          weight: 700

    - family: SofiaPro
      fonts:
        - asset: assets/fonts/Sofia-Pro-Medium.ttf
          weight: 500
